services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_KOFI_TIER_PAGE_URL: ${NEXT_PUBLIC_KOFI_TIER_PAGE_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./.gtfs:/app/.gtfs
      - ./prisma/.temp:/app/prisma/.temp
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: ["npm", "run", "start"]
    stdin_open: true
    tty: true
