services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_KOFI_TIER_PAGE_URL: ${NEXT_PUBLIC_KOFI_TIER_PAGE_URL}
        NEXT_PUBLIC_ADMIN_PUBKEY: ${NEXT_PUBLIC_ADMIN_PUBKEY}
        NEXT_PUBLIC_MODERATORS: ${NEXT_PUBLIC_MODERATORS}
        NEXT_PUBLIC_NOSTR_RELAYS: ${NEXT_PUBLIC_NOSTR_RELAYS}
        NEXT_PUBLIC_BUS_STOP_DISCUSSION_ID: ${NEXT_PUBLIC_BUS_STOP_DISCUSSION_ID}
        NEXT_PUBLIC_DISCUSSIONS_ENABLED: ${NEXT_PUBLIC_DISCUSSIONS_ENABLED}
        NEXT_PUBLIC_LOCATIONS_DATA_VERSION: ${NEXT_PUBLIC_LOCATIONS_DATA_VERSION}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: ["npm", "run", "start"]
    stdin_open: true
    tty: true
